version: "3.7"
services:
  dns:
    restart:
      on-failure
    build: docker-custom/unbound
    networks:
      - back
    ports:
      - "53:53/udp"
      - "53:53"
    dns:
      - "127.0.0.1"
      - "::1"
    container_name: dns-server
#    volumes:
#      - ./logs:/var/log/unbound

networks:
  back:
    name: net-dns
    driver: bridge

volumes:
  db-my-data: