version: "3.7"
services:

  dns: ### DNS-SERVER
    container_name: dns-server
    hostname: ns1.local.com
    restart:
      on-failure
    build: docker-custom/unbound
    networks:
      default:
        aliases:
          - ns1.local.com  ## Set Alias
    ports:
      - "53:53/udp"
      - "53:53"
    dns:
      - "127.0.0.1"
      - "::1"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
